server:
  port: 8083
#spring:
#  application:
#    name: back
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8080
  #      web-context-unify: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-rt2lrzfm.cd.tencentcdb.com:10007/limo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: item1234
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    default-property-inclusion: non_null
#  redis:
#    #    host: 192.168.223.128
#    #    port: 6379
#    cluster:
#      nodes:
#        - 192.168.223.128:6379
#        - 192.168.223.128:6380
#        - 192.168.223.128:6381
#        - 192.168.223.128:6382
#        - 192.168.223.128:6383
#        - 192.168.223.128:6384
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.woniuxy.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl