server:
  port: 8081
spring:
#配置数据源
  datasource:
    url: jdbc:mysql://cdb-rt2lrzfm.cd.tencentcdb.com:10007/limo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: item1234
    username: root
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
    driver-class-name: com.mysql.jdbc.Driver
